### ISSUE TITLE
HTTP used in documentation page

### ISSUE THREAD

**Issue by jimclark** [Lswbanban/BlueBrickParts#1]
The documentation pages use HTTP to link to each other, which causes Firefox and Chrome to flag them as 'insecure' and refuse to load them.  I can turn down some of the security settings to see the documentation pages again, but it would be better to update them to use HTTPS links everywhere.

**Comment by Lswbanban** [comment]
Hello Jimclark,

Thanks for noticing me, I will fix it asap.

Yours.

**Comment by Lswbanban** [comment]
Hello Jimclark,

I think, I've fixed all the http/https mixed issues, both on the website and in this git repo.
Please reopen the issue, if you still encounter problems.

Thanks.
